{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lightparser
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lightparser_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lightparser/lightparser_{{ version }}.tar.gz
  sha256: e6203b127764ac0af872c513cde8dd3c2e2461400e6a151ec771f88a45d7d49c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-knitr >=1.35
    - r-rlang
    - r-tibble
    - r-yaml
  run:
    - r-base
    - r-knitr >=1.35
    - r-rlang
    - r-tibble
    - r-yaml

test:
  commands:
    - $R -e "library('lightparser')"           # [not win]
    - "\"%R%\" -e \"library('lightparser')\""  # [win]

about:
  home: https://github.com/ThinkR-open/lightparser, https://thinkr-open.github.io/lightparser/
  license: MIT
  summary: 'Split your ''rmarkdown'' or ''quarto'' files by sections into a tibble: titles, text,
    chunks. Rebuild the file from the tibble.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: lightparser
# Title: From 'Rmarkdown' and 'Quarto' Files to Tibble and Back
# Version: 0.1.0
# Authors@R: c( person("Sebastien", "Rochette", , "sebastien@thinkr.fr", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1565-9313")), person("ThinkR", role = "cph") )
# Description: Split your 'rmarkdown' or 'quarto' files by sections into a tibble: titles, text, chunks. Rebuild the file from the tibble.
# License: MIT + file LICENSE
# URL: https://github.com/ThinkR-open/lightparser, https://thinkr-open.github.io/lightparser/
# BugReports: https://github.com/ThinkR-open/lightparser/issues
# Imports: knitr (>= 1.35), rlang, tibble, utils, yaml
# Suggests: callr, rmarkdown, testthat (>= 3.0.0)
# VignetteBuilder: knitr
# Config/fusen/version: 0.6.0
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-01-24 10:52:11 UTC; seb44
# Author: Sebastien Rochette [aut, cre] (<https://orcid.org/0000-0002-1565-9313>), ThinkR [cph]
# Maintainer: Sebastien Rochette <sebastien@thinkr.fr>
# Repository: CRAN
# Date/Publication: 2024-01-24 16:00:05 UTC
